---
- name: Run nginx
  hosts: all

  collections:
    - nginxinc.nginx_core

  tasks:
  - name: Install nginx
    ansible.builtin.import_role:
      name: nginx

  - name: Start nginx.
    service:
      name: nginx
      state: started
      use: service
