---
- name: run cowsay-nginx 
  hosts: all

  roles:
    - role: install-nginx
    - role: configure-cowsay-nginx

  tasks:
  - name: "start nginx"
    service: 
      name: nginx
      state: started
      use: service  # disclaimer on this shit