---

handlers:
- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: install nginx
  hosts: all
  become: true
  roles:
  - install-nginx

- name: Configure nginx
  hosts: all
  become: true
  roles:
  - cowsay-nginx-configuration
  notify: restart nginx

