version: '3'
services:
  workspace:
    build:
      context: .
      dockerfile: ansible_katas_workspace
    container_name: ansible_katas_workspace
    working_dir: /workspace
    volumes:
      - ${EXERCISE_PATH}/workspace:/workspace
      - "/var/run/docker.sock:/var/run/docker.sock"
  host-1:
    build:
      context: .
      dockerfile: ansible_katas_host
    container_name: ansible_katas_host_1
    environment:
      - NAME=ansible_katas_host_1
  host-2:
    build:
      context: .
      dockerfile: ansible_katas_host
    container_name: ansible_katas_host_2
    environment:
      - NAME=ansible_katas_host_2
