version: '3'
services:
  workspace:
    image: ghcr.io/verifa/ansible-katas:${IMAGE_TAG}
    container_name: ansible_katas_workspace
    privileged: true
    working_dir: /workspace
    volumes:
      - ${EXERCISE_PATH}/workspace:/workspace
      - "/var/run/docker.sock:/var/run/docker.sock"
  host-1:
    image: ghcr.io/verifa/ansible-katas:${IMAGE_TAG}
    container_name: ansible_katas_host_1
    environment:
      - NAME=ansible_katas_host_1
      - GROUP=loadbalancer
    ports:
      - "8080:8080"
  host-2:
    image: ghcr.io/verifa/ansible-katas:${IMAGE_TAG}
    container_name: ansible_katas_host_2
    environment:
      - NAME=ansible_katas_host_2
      - GROUP=backend
  host-3:
    image: ghcr.io/verifa/ansible-katas:${IMAGE_TAG}
    container_name: ansible_katas_host_3
    environment:
      - NAME=ansible_katas_host_3
      - GROUP=backend
