---
- name: Update Cache.
  ansible.builtin.package:
    update_cache: true

- name: Install nginx.
  ansible.builtin.package:
    name: nginx
    state: present

- name: Create www directory.
  file:
    path: /var/www/cowsay-site
    state: directory
    mode: '0775'
    owner: root  # "{{ ansible_user }}"
    group: root  # "{{ ansible_user }}"
