---
- name: Flush example
  hosts: all
  become: yes

  handlers:
    - name: handler 1
      shell: |
        echo "I'm a little handler"
      register: out

    - name: handler 2
      ansible.builtin.debug:
        msg: "{{ out.stdout_lines }}"

  tasks:
    - name: Task 1
      shell: |
        echo "example run"
      notify:
        - handler 1

    - name: Flush handlers
      meta: flush_handlers

    - name: Task 2
      shell: |
        echo "example run two"
      notify:
        - handler 2
