---
- name: install cowsay
  hosts: all
  become: yes

  handlers:
    - name: say something
      shell: |
        /usr/games/cowsay "I'm a little handler"
      register: out

    - name: print it
      ansible.builtin.debug:
        msg: "{{ out.stdout_lines }}"

  tasks:
    - name: Install cowsay.
      ansible.builtin.package:
        name: cowsay
        state: present
        update_cache: yes
      notify:
        - say something
        - print it
