---
- name: Install Cowsay
  hosts: all
  become: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Install cowsay.
      ansible.builtin.package:
        name: cowsay
        state: present
        update_cache: yes
