---
- name: Run cowsay-nginx
  hosts: all

  roles:
    - role: install-nginx
    - role: configure-cowsay-nginx

  tasks:
  - name: Start nginx.
    service:
      name: nginx
      state: started
      use: service
